---

- name: Install required packages for mysql
  apt:
    name: "{{ item }}"
    install_recommends: "yes"
  with_items:
    - "mysql-server"
    - "mysql-client"
    - "php7.1-mysql"

- name: mysql - config
  template:
    src: "my.cnf"
    dest: "/etc/mysql/my.cnf"

- name: Restart mysql service
  service:
    name: mysql
    state: restarted