---
- name: Update apt cache # apt-get update
  apt:
    update_cache: yes

- name: Install required packages for mysql # apt-get install apt-transport-https ca-certificates curl software-properties-common
  apt:
    name: "{{ item }}"
    install_recommends: "yes"
  with_items:
    - "mysql-server"
    - "mysql-client"
    - "php7.1-mysql"

- name: mysql - config
  template:
    src: "my.cnf"
    dest: "/etc/mysql/my.cnf"

- name: Restart mysql service
  service:
    name: mysql
    state: restarted